before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
      #- windows
    gcflags:
release:
  prerelease: auto
  draft: false
archives:
  - replacements:
      #darwin: Darwin
      linux: Linux
      #windows: Windows
      #386: i386
      amd64: x86_64
    files:
      - LICENSE
      - Readme.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
